### ISSUE TITLE
Rails bundle install failure

### ISSUE THREAD

**Issue by trans** [postmodern/ruby-install#137]
I'm not 100% clear where the problem actually lies just yet, but one thing I did notice when using `bundle install` on a fresh Rails projects was that my systems ruby was being used to compile extensions instead of the chruby version.

```
$ chruby
   ruby-2.0.0-p247
 * ruby-2.1.0
```

```
$ ruby -v
ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-linux]
```

```
$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching additional metadata from https://rubygems.org/..
Using rake 10.1.1
Using i18n 0.6.9

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb 
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from extconf.rb:1:in `<main>'


Gem files will remain installed in /home/trans/.gem/ruby/2.1.0/gems/json-1.8.1 for inspection.
Results logged to /home/trans/.gem/ruby/2.1.0/gems/json-1.8.1/ext/json/ext/generator/gem_make.out
An error occurred while installing json (1.8.1), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.1'` succeeds before bundling.
```

How do I correct this?

**Comment by mjacobus** [comment]
I had the same problem. Thanks @postmodern
